# This file was generated by GoReleaser. DO NOT EDIT.
cask "misha" do
  desc "misha - ssh connection manager"
  homepage ""
  version "0.8.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "misha"
  manpage "manpages/misha.1.gz"

  on_macos do
    on_intel do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.2/misha_Darwin_x86_64.tar.gz"
      sha256 "711960f918625cf7b75ea8775b2f997f21aafa311d0dcb94c9a431c933bb4a4b"
    end
    on_arm do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.2/misha_Darwin_arm64.tar.gz"
      sha256 "f3c476ed0ed632d71b5d9eac516be09949ab6d14a56a68cb76f79293fcb8b242"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.2/misha_Linux_x86_64.tar.gz"
      sha256 "6c3134fe79638cd2e15dc322eaf7faf53f237217af7e973fb3d016c0a7e5f7fd"
    end
    on_arm do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.2/misha_Linux_arm64.tar.gz"
      sha256 "b23bae2dce7e33f717b4f88a949bf2514b1b068174d1335a280ab8264e93def7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/misha"]
    end
  end

  # No zap stanza required
end
