# This file was generated by GoReleaser. DO NOT EDIT.
cask "misha" do
  desc "misha - ssh connection manager"
  homepage ""
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "misha"
  manpage "manpages/misha.1.gz"

  on_macos do
    on_intel do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.0/misha_Darwin_x86_64.tar.gz"
      sha256 "5c6826779427927bb60dbe9fe664d74fd9acefd7f17e673edd68a761d94e4558"
    end
    on_arm do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.0/misha_Darwin_arm64.tar.gz"
      sha256 "bfcfacaac1697804065e007fb81bbc63a312a196a8f652406afbef9aaf55e9ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.0/misha_Linux_x86_64.tar.gz"
      sha256 "51662ec56e4622be5e34484946e1b8e48166688d6d8ad36740fde6c4e4e563cd"
    end
    on_arm do
      url "https://github.com/misha-ssh/cli/releases/download/v0.8.0/misha_Linux_arm64.tar.gz"
      sha256 "ed534c019663c75976c0ccfee942ceb3e9ee8fd107c03c7f7d08657a0ef677f0"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/misha"]
    end
  end

  # No zap stanza required
end
