# This file was generated by GoReleaser. DO NOT EDIT.
cask "misha" do
  desc "misha - ssh connection manager"
  homepage ""
  version "0.7.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "misha"
  manpage "manpages/misha.1.gz"

  on_macos do
    on_intel do
      url "https://github.com/misha-ssh/cli/releases/download/v0.7.9/misha_Darwin_x86_64.tar.gz"
      sha256 "10ceb0d6cf8fd7565bcdeb6ff81c7de5a63d0a65d21200a1b8e294086a64b778"
    end
    on_arm do
      url "https://github.com/misha-ssh/cli/releases/download/v0.7.9/misha_Darwin_arm64.tar.gz"
      sha256 "cc37a244ca138ffebe5f820df9aa6ece9d8b7508ed6cf9ca1d585b207daf3666"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/misha-ssh/cli/releases/download/v0.7.9/misha_Linux_x86_64.tar.gz"
      sha256 "306229bb285466cded13ed0be84ad79e6da1302e28cbc6e30715db5c711ad1c0"
    end
    on_arm do
      url "https://github.com/misha-ssh/cli/releases/download/v0.7.9/misha_Linux_arm64.tar.gz"
      sha256 "70171e3f9dcbf5723df22253ce81a7e8c8d942d57c2db4c85482c7a5e235a7aa"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/misha"]
    end
  end

  # No zap stanza required
end
